-- AddEnumValues: ProjectCategory
ALTER TYPE "ProjectCategory" ADD VALUE IF NOT EXISTS 'STREAMING';
ALTER TYPE "ProjectCategory" ADD VALUE IF NOT EXISTS 'CONTRACTS';
ALTER TYPE "ProjectCategory" ADD VALUE IF NOT EXISTS 'PERSONAL';
ALTER TYPE "ProjectCategory" ADD VALUE IF NOT EXISTS 'PROTOTYPES';

-- AddEnumValues: SkillCategory
ALTER TYPE "SkillCategory" ADD VALUE IF NOT EXISTS 'DATABASE';
ALTER TYPE "SkillCategory" ADD VALUE IF NOT EXISTS 'MOBILE';
ALTER TYPE "SkillCategory" ADD VALUE IF NOT EXISTS 'OTHER';

-- AddColumns: Experience
ALTER TABLE "Experience" ADD COLUMN IF NOT EXISTS "techStack" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Experience" ADD COLUMN IF NOT EXISTS "location" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Experience" ADD COLUMN IF NOT EXISTS "period" TEXT NOT NULL DEFAULT '';

-- AddColumns: Blog
ALTER TABLE "Blog" ADD COLUMN IF NOT EXISTS "excerpt" TEXT;
ALTER TABLE "Blog" ADD COLUMN IF NOT EXISTS "category" TEXT;

-- AddColumns: SystemDesign
ALTER TABLE "SystemDesign" ADD COLUMN IF NOT EXISTS "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
